### ISSUE TITLE
'LinkPlugin' is already registered.

### ISSUE THREAD

**Issue by hapesurya** [django-cms/djangocms-link#224]
Dear All,

I faced an error when installing djangocms-link with pip install djangocms-link command as I wrote below:

raise PluginAlreadyRegistered(
cms.exceptions.PluginAlreadyRegistered: Cannot register <class 'djangocms_link.cms_plugins.LinkPlugin'>, a plugin with this name ('LinkPlugin') is already registered.

And this LinkPlugin class comes from cms_plugins.py.

===

I am currently just following this page:

https://docs.django-cms.org/en/latest/how_to/install.html#miscellaneous-plugins

to install miscellaneous plugins. Below is my pip list:

Package                    Version
-------------------------- ----------
appdirs                    1.4.4
asgiref                    3.7.2
certifi                    2023.11.17
charset-normalizer         3.3.2
cssselect2                 0.7.0
Django                     4.2.8
django-appconf             1.0.6
django-classy-tags         4.1.0
django-cms                 3.11.4
django-entangled           0.5.4
django-filer               3.1.1
django-formtools           2.4.1
django-parler              2.3
django-polymorphic         3.1.0
django-sekizai             4.1.0
django-select2             8.1.2
django-treebeard           4.7
djangocms-admin-style      3.2.6
djangocms-attributes-field 3.0.0
djangocms-file             3.0.1
djangocms-frontend         1.2.0
djangocms-googlemap        2.2.0
djangocms-icon             2.1.0
djangocms-link             3.1.1
djangocms-picture          4.1.1
djangocms-snippet          3.1.1
djangocms-style            3.1.0
djangocms-text-ckeditor    5.1.5
djangocms-video            3.1.0
easy-thumbnails            2.8.5
fake-useragent             1.4.0
html5lib                   1.1
idna                       3.6
iniconfig                  2.0.0
lxml                       4.9.3
markdown-it-py             3.0.0
marshmallow                3.20.1
mdurl                      0.1.2
packaging                  23.2
Pillow                     10.1.0
pip                        23.3.1
pipdate                    0.5.6
pluggy                     1.3.0
Pygments                   2.17.2
pytest                     7.4.3
python-dotenv              1.0.0
reportlab                  4.0.7
requests                   2.31.0
rich                       13.7.0
setuptools                 66.1.1
six                        1.16.0
sqlparse                   0.4.4
svglib                     1.5.1
termcolor                  2.4.0
tinycss2                   1.2.1
urllib3                    2.1.0
webencodings               0.5.1

Do you happen to know how to solve this? 

Thank you.

**Comment by aacimov** [comment]
I've accidentally seen your post but the problem is you have `djangocms_link` and `djangocms_frontend` installed.

`djangocms_frontend` package is used in the new Django CMS v4, you have Django CMS 3.11.4 installed.

Option 1

1. Remove `djangocms_frontend` from your installed apps (and do a pip uninstall `djangocms_frontend`)
2. Keep using Django CMS v3

Option 2

1. Remove `djangocms_link`, `djangocms_picture` (for these 2 I know don't work with Django CMS v4) and maybe some other packages that are not compatible with the new CMS v4
2. Upgrade to django-cms==4.1.0
3. Add `djangocms_frontend.contrib.link` and `djangocms_frontend.contrib.image` to your `INSTALLED_APPS`

**NOTE:** If you already have your database loaded and filled, Option 1 is easier, Django CMS v4 introduced lots of new dependencies and you will have to start from scratch or migrate your data. Be sure to read the docs on how to install CMS v4 from the official documentation's page.

I hope it helped.

**Comment by hapesurya** [comment]
Love this, thanks for your explanation.
